name: deploy-web-app
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup AWS
      run: |
          mkdir ./.aws
          touch ./.aws/credentials
          echo '${{ secrets.AWS_CREDENTIALS_FILE }}' > ./.aws/credentials 
    - name: ECR
      env:
        AWS_SHARED_CREDENTIALS_FILE: ./.aws/credentials
        AWS_PROFILE: default
        AWS_DEFAULT_REGION: us-east-2
      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 359409690900.dkr.ecr.us-east-2.amazonaws.com
        docker build -t crec_app .
        docker tag crec-app:latest 359409690900.dkr.ecr.us-east-2.amazonaws.com/crec-app:latest
        docker push 359409690900.dkr.ecr.us-east-2.amazonaws.com/crec-app:latest


